export const BUSINESS_CATEGORIES = [
  {
    id: 'tienda',
    name: 'Tienda / Abarrotes',
    emoji: '🏪',
    description: 'Tienda de barrio, minimarket, bodega',
    theme: {
      sidebar: 'bg-emerald-600',
      sidebarIcon: 'bg-emerald-500',
      navActive: 'bg-emerald-50 text-emerald-700',
      navActiveIcon: 'text-emerald-600',
      mobileNavActive: 'text-emerald-600',
      headerBg: 'bg-emerald-600',
      subtitleColor: 'text-emerald-200',
      badgeBg: 'bg-emerald-100 text-emerald-700',
      primaryBtn: 'from-emerald-500 to-emerald-700',
      settingsCard: 'from-emerald-500 to-emerald-700',
      borderFocus: 'focus:border-emerald-500',
      logoBg: 'bg-emerald-500',
      cardGradients: [
        'from-emerald-400 to-emerald-600',
        'from-teal-400 to-emerald-600',
        'from-green-400 to-emerald-500',
        'from-emerald-500 to-teal-600',
        'from-teal-500 to-green-600',
        'from-green-500 to-teal-600',
      ],
    },
    defaultCategories: ['Bebidas', 'Lácteos', 'Snacks y dulces', 'Carnes', 'Granos y cereales', 'Limpieza', 'Higiene personal', 'Condimentos', 'Otros'],
  },
  {
    id: 'panaderia',
    name: 'Panadería / Repostería',
    emoji: '🥖',
    description: 'Pan, pasteles, tortas, repostería',
    theme: {
      sidebar: 'bg-amber-700',
      sidebarIcon: 'bg-amber-600',
      navActive: 'bg-amber-50 text-amber-700',
      navActiveIcon: 'text-amber-600',
      mobileNavActive: 'text-amber-600',
      headerBg: 'bg-amber-700',
      subtitleColor: 'text-amber-200',
      badgeBg: 'bg-amber-100 text-amber-700',
      primaryBtn: 'from-amber-500 to-amber-700',
      settingsCard: 'from-amber-500 to-amber-700',
      borderFocus: 'focus:border-amber-500',
      logoBg: 'bg-amber-600',
      cardGradients: [
        'from-amber-400 to-amber-600',
        'from-yellow-400 to-amber-600',
        'from-orange-400 to-amber-600',
        'from-amber-500 to-orange-600',
        'from-yellow-500 to-amber-600',
        'from-orange-400 to-yellow-500',
      ],
    },
    defaultCategories: ['Pan', 'Tortas y pasteles', 'Galletas', 'Empanadas', 'Bebidas', 'Dulces', 'Otros'],
  },
  {
    id: 'licorera',
    name: 'Licorera / Distribuidora',
    emoji: '🍺',
    description: 'Licores, cervezas, bebidas alcohólicas',
    theme: {
      sidebar: 'bg-purple-800',
      sidebarIcon: 'bg-purple-700',
      navActive: 'bg-purple-50 text-purple-700',
      navActiveIcon: 'text-purple-600',
      mobileNavActive: 'text-purple-600',
      headerBg: 'bg-purple-800',
      subtitleColor: 'text-purple-300',
      badgeBg: 'bg-purple-100 text-purple-700',
      primaryBtn: 'from-purple-600 to-purple-800',
      settingsCard: 'from-purple-600 to-purple-900',
      borderFocus: 'focus:border-purple-500',
      logoBg: 'bg-purple-700',
      cardGradients: [
        'from-purple-500 to-purple-700',
        'from-violet-500 to-purple-700',
        'from-indigo-500 to-purple-600',
        'from-purple-600 to-indigo-700',
        'from-violet-600 to-indigo-700',
        'from-indigo-500 to-violet-600',
      ],
    },
    defaultCategories: ['Cervezas', 'Whiskey', 'Ron', 'Vinos', 'Vodka', 'Refrescos', 'Agua', 'Otros'],
  },
  {
    id: 'ferreteria',
    name: 'Ferretería / Materiales',
    emoji: '🔧',
    description: 'Herramientas, materiales de construcción',
    theme: {
      sidebar: 'bg-slate-800',
      sidebarIcon: 'bg-orange-600',
      navActive: 'bg-orange-50 text-orange-700',
      navActiveIcon: 'text-orange-600',
      mobileNavActive: 'text-orange-600',
      headerBg: 'bg-slate-800',
      subtitleColor: 'text-slate-400',
      badgeBg: 'bg-orange-100 text-orange-700',
      primaryBtn: 'from-orange-500 to-slate-700',
      settingsCard: 'from-slate-600 to-slate-900',
      borderFocus: 'focus:border-orange-500',
      logoBg: 'bg-orange-600',
      cardGradients: [
        'from-slate-600 to-slate-800',
        'from-orange-500 to-orange-700',
        'from-slate-500 to-orange-700',
        'from-orange-600 to-slate-700',
        'from-gray-600 to-slate-800',
        'from-orange-400 to-slate-600',
      ],
    },
    defaultCategories: ['Herramientas', 'Tornillería', 'Pinturas', 'Electricidad', 'Plomería', 'Construcción', 'Cemento', 'Otros'],
  },
  {
    id: 'farmacia',
    name: 'Farmacia / Botica',
    emoji: '💊',
    description: 'Medicamentos, salud, higiene',
    theme: {
      sidebar: 'bg-blue-700',
      sidebarIcon: 'bg-blue-600',
      navActive: 'bg-blue-50 text-blue-700',
      navActiveIcon: 'text-blue-600',
      mobileNavActive: 'text-blue-600',
      headerBg: 'bg-blue-700',
      subtitleColor: 'text-blue-200',
      badgeBg: 'bg-blue-100 text-blue-700',
      primaryBtn: 'from-blue-500 to-blue-700',
      settingsCard: 'from-blue-500 to-blue-800',
      borderFocus: 'focus:border-blue-500',
      logoBg: 'bg-blue-600',
      cardGradients: [
        'from-blue-500 to-blue-700',
        'from-cyan-500 to-blue-600',
        'from-sky-500 to-blue-600',
        'from-blue-600 to-cyan-700',
        'from-cyan-400 to-blue-600',
        'from-sky-400 to-cyan-600',
      ],
    },
    defaultCategories: ['Medicamentos', 'Vitaminas', 'Bebés', 'Higiene personal', 'Primeros auxilios', 'Otros'],
  },
  {
    id: 'restaurante',
    name: 'Restaurante / Comedor',
    emoji: '🍽️',
    description: 'Alimentos, comidas, menú del día',
    theme: {
      sidebar: 'bg-red-700',
      sidebarIcon: 'bg-red-600',
      navActive: 'bg-red-50 text-red-700',
      navActiveIcon: 'text-red-600',
      mobileNavActive: 'text-red-600',
      headerBg: 'bg-red-700',
      subtitleColor: 'text-red-200',
      badgeBg: 'bg-red-100 text-red-700',
      primaryBtn: 'from-red-500 to-red-700',
      settingsCard: 'from-red-500 to-red-800',
      borderFocus: 'focus:border-red-500',
      logoBg: 'bg-red-600',
      cardGradients: [
        'from-red-500 to-red-700',
        'from-orange-500 to-red-600',
        'from-rose-500 to-red-700',
        'from-red-600 to-orange-700',
        'from-orange-400 to-rose-600',
        'from-rose-400 to-orange-600',
      ],
    },
    defaultCategories: ['Platos principales', 'Sopas', 'Entradas', 'Bebidas', 'Postres', 'Menú del día', 'Extras'],
  },
  {
    id: 'carniceria',
    name: 'Carnicería / Res',
    emoji: '🥩',
    description: 'Carnes, embutidos, mariscos',
    theme: {
      sidebar: 'bg-rose-700',
      sidebarIcon: 'bg-rose-600',
      navActive: 'bg-rose-50 text-rose-700',
      navActiveIcon: 'text-rose-600',
      mobileNavActive: 'text-rose-600',
      headerBg: 'bg-rose-700',
      subtitleColor: 'text-rose-200',
      badgeBg: 'bg-rose-100 text-rose-700',
      primaryBtn: 'from-rose-500 to-rose-700',
      settingsCard: 'from-rose-500 to-rose-800',
      borderFocus: 'focus:border-rose-500',
      logoBg: 'bg-rose-600',
      cardGradients: [
        'from-rose-500 to-rose-700',
        'from-red-500 to-rose-700',
        'from-pink-500 to-rose-600',
        'from-rose-600 to-red-800',
        'from-red-400 to-rose-600',
        'from-pink-400 to-red-600',
      ],
    },
    defaultCategories: ['Res', 'Pollo', 'Cerdo', 'Embutidos', 'Mariscos', 'Otros cortes'],
  },
  {
    id: 'fruteria',
    name: 'Frutería / Verdulería',
    emoji: '🥦',
    description: 'Frutas, verduras, productos frescos',
    theme: {
      sidebar: 'bg-green-700',
      sidebarIcon: 'bg-green-600',
      navActive: 'bg-green-50 text-green-700',
      navActiveIcon: 'text-green-600',
      mobileNavActive: 'text-green-600',
      headerBg: 'bg-green-700',
      subtitleColor: 'text-green-200',
      badgeBg: 'bg-green-100 text-green-700',
      primaryBtn: 'from-green-500 to-green-700',
      settingsCard: 'from-green-500 to-green-800',
      borderFocus: 'focus:border-green-500',
      logoBg: 'bg-green-600',
      cardGradients: [
        'from-green-500 to-green-700',
        'from-lime-500 to-green-600',
        'from-emerald-500 to-green-700',
        'from-green-600 to-lime-700',
        'from-lime-400 to-emerald-600',
        'from-emerald-400 to-lime-600',
      ],
    },
    defaultCategories: ['Frutas', 'Verduras', 'Tubérculos', 'Hierbas', 'Otros'],
  },
  {
    id: 'papeleria',
    name: 'Papelería / Librería',
    emoji: '📚',
    description: 'Útiles escolares, papelería, imprenta',
    theme: {
      sidebar: 'bg-indigo-700',
      sidebarIcon: 'bg-indigo-600',
      navActive: 'bg-indigo-50 text-indigo-700',
      navActiveIcon: 'text-indigo-600',
      mobileNavActive: 'text-indigo-600',
      headerBg: 'bg-indigo-700',
      subtitleColor: 'text-indigo-200',
      badgeBg: 'bg-indigo-100 text-indigo-700',
      primaryBtn: 'from-indigo-500 to-indigo-700',
      settingsCard: 'from-indigo-500 to-indigo-800',
      borderFocus: 'focus:border-indigo-500',
      logoBg: 'bg-indigo-600',
      cardGradients: [
        'from-indigo-500 to-indigo-700',
        'from-blue-500 to-indigo-600',
        'from-violet-500 to-indigo-600',
        'from-indigo-600 to-blue-700',
        'from-blue-400 to-violet-600',
        'from-violet-400 to-blue-600',
      ],
    },
    defaultCategories: ['Cuadernos', 'Bolígrafos y lápices', 'Libros', 'Arte y dibujo', 'Impresión', 'Otros'],
  },
  {
    id: 'ropa',
    name: 'Boutique / Ropa',
    emoji: '👗',
    description: 'Ropa, moda, calzado, accesorios',
    theme: {
      sidebar: 'bg-pink-700',
      sidebarIcon: 'bg-pink-600',
      navActive: 'bg-pink-50 text-pink-700',
      navActiveIcon: 'text-pink-600',
      mobileNavActive: 'text-pink-600',
      headerBg: 'bg-pink-700',
      subtitleColor: 'text-pink-200',
      badgeBg: 'bg-pink-100 text-pink-700',
      primaryBtn: 'from-pink-500 to-pink-700',
      settingsCard: 'from-pink-500 to-fuchsia-700',
      borderFocus: 'focus:border-pink-500',
      logoBg: 'bg-pink-600',
      cardGradients: [
        'from-pink-500 to-pink-700',
        'from-fuchsia-500 to-pink-600',
        'from-rose-500 to-pink-700',
        'from-pink-600 to-fuchsia-700',
        'from-fuchsia-400 to-rose-600',
        'from-rose-400 to-fuchsia-600',
      ],
    },
    defaultCategories: ['Damas', 'Caballeros', 'Niños', 'Calzado', 'Accesorios', 'Ropa interior', 'Otros'],
  },
  {
    id: 'otro',
    name: 'Otro negocio',
    emoji: '🏬',
    description: 'Otro tipo de negocio',
    theme: {
      sidebar: 'bg-emerald-600',
      sidebarIcon: 'bg-emerald-500',
      navActive: 'bg-emerald-50 text-emerald-700',
      navActiveIcon: 'text-emerald-600',
      mobileNavActive: 'text-emerald-600',
      headerBg: 'bg-emerald-600',
      subtitleColor: 'text-emerald-200',
      badgeBg: 'bg-emerald-100 text-emerald-700',
      primaryBtn: 'from-emerald-500 to-emerald-700',
      settingsCard: 'from-emerald-500 to-emerald-700',
      borderFocus: 'focus:border-emerald-500',
      logoBg: 'bg-emerald-500',
      cardGradients: [
        'from-emerald-400 to-emerald-600',
        'from-teal-400 to-emerald-600',
        'from-green-400 to-emerald-500',
        'from-emerald-500 to-teal-600',
        'from-teal-500 to-green-600',
        'from-green-500 to-teal-600',
      ],
    },
    defaultCategories: ['Bebidas', 'Lácteos', 'Snacks', 'Limpieza', 'Otros'],
  },
];

export const DEFAULT_CATEGORY_ID = 'tienda';

export function getCategoryById(id) {
  return BUSINESS_CATEGORIES.find((c) => c.id === id) || BUSINESS_CATEGORIES[0];
}

export function getTheme(businessCategory) {
  return getCategoryById(businessCategory).theme;
}
